# Available location format placeholders:
# %country%: Vietnam              # %city%: Hanoi
# %countryCode%: VN               # %timezone%: Asia/Bangkok
# %region%: HN                    # %isp%: VietNam Post and Telecom Corporation
# %regionName%: Hanoi

# proxycheck.io
# vpnapi.io
# funkemunky.cc
# iphub.info
enable: true
debug: false
location:
  check: true
  format: "%city% - %regionName% - %countryCode%"
score:
  kick:
    at: 75
    color: "&c"
  alert:
    at: 40
    color: "&6"
  safe:
    color: "&a"
api:
  proxycheck:
    enable: true
    key: none
  vpnapi:
    enable: true
    key: none
  funkemunky:
    enable: true
  iphub:
    enable: true
    key: none
staff: