name: AntiProxy
main: ml.thelt.antiproxy.Main
version: pre_RTM-build-1.0
api-version: 1.17
description: Prevent Players connecting to server with Proxies/VPN
author: TheLT
website: https://thiccsmp.qtpc.tech
commands:
  ap:
    description: AntiProxy plugin command
    aliases: ["antiproxy","antivpn"]
    permission: antiproxy.admin