name: AntiProxy
main: ml.thelt.antiproxy.Main
version: 1.0-pre_Release
api-version: 1.17
description: Prevent Players connecting to server with Proxies/VPN
author: TheLT
website: https://thiccsmp.qtpc.tech
# depend: [LoginSecurity]
commands:
  ap:
    description: AntiProxy plugin command
    aliases: ["antiproxy","antivpn"]
    permission: antiproxy.admin
  player:
    description: AntiProxy Player command
    permission: antiproxy.admin